package proyecto1_201900122_vj2020;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */
public class CARGAR_DATOS extends javax.swing.JFrame {
    //AQUÍ NO PONGAS NINGÚN ARREGLO A USAR!! VAS A ARRUINAR EL PROYECTO.
    //A LA DISTANCIA UN ABRAZO VIRTUAL :3

    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form VENTANA_CARGAR_DATOS
     */
    public CARGAR_DATOS() {
        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CARGAR DATOS");

        jButton1.setFont(new java.awt.Font("Algerian", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setLabel("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Algerian", 0, 16)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 0, 153));
        cancelar.setLabel("cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //   SOLICITAR_SEGURO_AUTOMAS solicitud_seguro = new SOLICITAR_SEGURO_AUTOMAS();
        String[] linea = jTextArea1.getText().split("\n");
        for (String dato : linea) {
            String[] info = dato.split(",");
            switch (info[0]) {
                case "TIPO":
                    DATOS_MASIVOS.guardar_tipo(info[1], info[2]);
                    DATOS_MASIVOS.setPosicion_tipo(DATOS_MASIVOS.getPosicion_tipo() + 1);
                    break;
                case "MODELO":
                    DATOS_MASIVOS.guardar_modelo(info[1], info[2]);
                    DATOS_MASIVOS.setPosicion_modelo(DATOS_MASIVOS.getPosicion_modelo() + 1);
                    break;
                case "MARCA":
                    DATOS_MASIVOS.guardar_marca(info[1], info[2]);
                    DATOS_MASIVOS.setPosicion_marca(DATOS_MASIVOS.getPosicion_marca() + 1);
                    break;
                case "LINEA":
                    DATOS_MASIVOS.guardar_linea(info[1], info[2]);
                    DATOS_MASIVOS.setPosicion_linea(DATOS_MASIVOS.getPosicion_linea() + 1);
                    break;
                case "USO":
                    DATOS_MASIVOS.guardar_uso(info[1], info[2]);
                    DATOS_MASIVOS.setPosicion_uso(DATOS_MASIVOS.getPosicion_uso() + 1);
                    break;
                case "MECANICA":
                    DATOS_MASIVOS.guardar_mecanica(info[1], info[2]);
                    DATOS_MASIVOS.setPosicion_mecanica(DATOS_MASIVOS.getPosicion_mecanica() + 1);
                    break;
                case "REPUESTO":
                    DATOS_MASIVOS.guardar_repuesto(info[1], info[2]);
                    DATOS_MASIVOS.setPosicion_repuesto(DATOS_MASIVOS.getPosicion_repuesto() + 1);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "NO SE HA INGRESADO LA INFORMACION CON LA SINTAXIS CORRECTA");
                    break;
            }
        }
        JOptionPane.showMessageDialog(null, "SE HA CARGADO LA INFORMACION" + "\n EN LA VENTANA DE SOLICITUAR SEGURO");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        jTextArea1.setText("");
        this.setVisible(false);
        MENU_PRINCIPAL regresar = new MENU_PRINCIPAL();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CARGAR_DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CARGAR_DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CARGAR_DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CARGAR_DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CARGAR_DATOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/dos.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
