/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_201900122_vj2020;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */
public class SOLICITUDES_DE_SEGURO extends javax.swing.JFrame {
//AQUÍ NO PONGAS NINGÚN ARREGLO A USAR!! VAS A ARRUINAR EL PROYECTO.
    //A LA DISTANCIA UN ABRAZO VIRTUAL :3

    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form SOLICITUDES_DE_SEGURO
     */
    public SOLICITUDES_DE_SEGURO() {
        this.setContentPane(fondo);
        initComponents();
        System.out.println("almacenado DPI:" + datos_solicitud_seguro.getA()[0]);
        for (int i = 0; i < datos_solicitud_seguro.getNoSolicitud(); i++) {
            if (datos_solicitud_seguro.getA()[i] != null) {
                String dato_auxiliar = DATOS_MASIVOS.getTipo_nombre()[i];
                this.tabla.setValueAt(i + 1, i, 0);
                this.tabla.setValueAt(datos_solicitud_seguro.getA()[i], i, 1);
                this.tabla.setValueAt(datos_solicitud_seguro.getB()[i], i, 2);
                this.tabla.setValueAt(datos_solicitud_seguro.getC()[i], i, 3);
                this.tabla.setValueAt(datos_solicitud_seguro.getD()[i], i, 4);
                this.tabla.setValueAt(datos_solicitud_seguro.getE()[i], i, 5);
                this.tabla.setValueAt(datos_solicitud_seguro.getF()[i], i, 6);
                this.tabla.setValueAt(datos_solicitud_seguro.getG()[i], i, 7);
                this.tabla.setValueAt(datos_solicitud_seguro.getH()[i], i, 8);
            }else
            if(datos_solicitud_seguro.getA()[i] == null){
                this.tabla.setValueAt("EL", i, 0);
                this.tabla.setValueAt("PROCESO", i, 1);
                this.tabla.setValueAt("DE", i, 2);
                this.tabla.setValueAt("SOLICITUD", i, 3);
                this.tabla.setValueAt("DE", i, 4);
                this.tabla.setValueAt("SEGURO", i, 5);
                this.tabla.setValueAt("YA", i, 6);
                this.tabla.setValueAt("SE", i, 7);
                this.tabla.setValueAt("TERMINO", i, 8);
            }
           
        }

        //    this.tabla.addComponentListener(cl);
        //INTRODUCIR EN TABLA INFORMACION DE datos_solicitud_seguro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Solicitud de seguro");

        jButton2.setFont(new java.awt.Font("Algerian", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("arpobar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Algerian", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("rechazar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Algerian", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 153));
        jButton4.setText("cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. ", "DPI", "NOMBRE", "TELEFONO", "TIPO", "DESCRIPCION", "MONTO", "POLIZA", "DEDUCIBLE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton2)
                .addGap(150, 150, 150)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int columna = this.tabla.getSelectedRow();
        if(this.tabla.getValueAt(columna, 0)=="EL" || this.tabla.getValueAt(columna, 0)==null){
                    JOptionPane.showMessageDialog(null, "ERROR, no ha seleccionado una fila con una solicitud pendiente");
        }else{
        String DPI = (String) this.tabla.getValueAt(columna, 1);
        String NOMBRE = (String) this.tabla.getValueAt(columna, 2);
        String TELEFONO = (String) this.tabla.getValueAt(columna, 3);
        String TIPO = (String) this.tabla.getValueAt(columna, 4);
        String DESCRIPCION = (String) this.tabla.getValueAt(columna, 5);
        String MONTO = (String) this.tabla.getValueAt(columna, 6);
        String POLIZA = (String) this.tabla.getValueAt(columna, 7);
        String DEDUCIBLE = (String) this.tabla.getValueAt(columna, 8);
        datos_asegurado.almacenar(DPI, NOMBRE, TELEFONO, TIPO, DESCRIPCION, MONTO, POLIZA, DEDUCIBLE);
        datos_asegurado.setContador_Aprobados(datos_asegurado.getContador_Aprobados() + 1);
        JOptionPane.showMessageDialog(null, "se registro del DPI: "+datos_asegurado.getDPI()[datos_asegurado.getContador_Aprobados()-1]+", No. de Usuario: "+datos_asegurado.getContador_Aprobados());
        datos_asegurado.imprimir_almacenados();
       int posicion = (int) this.tabla.getValueAt(columna, 0);
       System.out.println("posicion de tabla "+posicion);
       System.out.println("posicion del arreglo: "+(posicion-1));
       datos_solicitud_seguro.eliminar_datos(posicion-1);
        for(int i=0; i<9; i++){
        this.tabla.setValueAt(null, columna, i);
        }
        }
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int columna = this.tabla.getSelectedRow();
        if(this.tabla.getValueAt(columna, 0)=="EL" || this.tabla.getValueAt(columna, 0)==null){
                    JOptionPane.showMessageDialog(null, "ERROR, no ha seleccionado una fila con una solicitud pendiente");
        }else{
        int posicion = (int) this.tabla.getValueAt(columna, 0);
       JOptionPane.showMessageDialog(null, "se RECHAZO del DPI: "+datos_solicitud_seguro.getA()[posicion-1]);
        datos_solicitud_seguro.eliminar_datos(posicion-1);
        for(int i=0; i<9; i++){
        this.tabla.setValueAt(null, columna, i);
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        MENU_PRINCIPAL regresar = new MENU_PRINCIPAL();
        regresar.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SOLICITUDES_DE_SEGURO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SOLICITUDES_DE_SEGURO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SOLICITUDES_DE_SEGURO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SOLICITUDES_DE_SEGURO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SOLICITUDES_DE_SEGURO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/cuatro.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
            super.paint(g);
        }
    }
}
